/*
 * External_interrupt_configuration.h
 *
 *  Created on: Apr 2, 2023
 *      Author: ss210
 */

#ifndef MCAL_EXTERNAL_INTERRUPT_EXTERNAL_INTERRUPT_CONFIGURATION_H_
#define MCAL_EXTERNAL_INTERRUPT_EXTERNAL_INTERRUPT_CONFIGURATION_H_



#endif /* MCAL_EXTERNAL_INTERRUPT_EXTERNAL_INTERRUPT_CONFIGURATION_H_ */
