/*
 * led1_configuration.h
 *
 *  Created on: Mar 31, 2023
 *      Author: ss210
 */

#ifndef HAL_HEATING_ELEMENT_LED_CONFIGURATION_H_
#define HAL_HEATING_ELEMENT_LED_CONFIGURATION_H_



#endif /* HAL_HEATING_ELEMENT_LED_HEATING_ELEMENT_LED_CONFIGURATION_H_ */
